SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

		 CREATE VIEW [prodcopy].[vw_Contact] AS 
SELECT accountid AS Id, accountidname, accountidyominame, accountrolecode, accountrolecodename, address1_addressid,
 address1_addresstypecode, address1_addresstypecodename, address1_city, address1_composite, address1_country, 
 address1_county, address1_fax, address1_freighttermscode, address1_freighttermscodename, address1_latitude, 
 address1_line1, address1_line2, address1_line3, address1_longitude, address1_name, address1_postalcode,
 address1_postofficebox, address1_primarycontactname, address1_shippingmethodcode, address1_shippingmethodcodename,
  address1_stateorprovince, address1_telephone1, address1_telephone2, address1_telephone3, address1_upszone, 
  address1_utcoffset, address2_addressid, address2_addresstypecode, address2_addresstypecodename, 
  address2_city, address2_composite, address2_country, address2_county, address2_fax, address2_freighttermscode, 
  address2_freighttermscodename, address2_latitude, address2_line1, address2_line2, address2_line3, address2_longitude, 
  address2_name, address2_postalcode, address2_postofficebox, address2_primarycontactname, address2_shippingmethodcode, 
  address2_shippingmethodcodename, address2_stateorprovince, address2_telephone1, address2_telephone2, address2_telephone3, 
  address2_upszone, address2_utcoffset, address3_addressid, address3_addresstypecode, address3_addresstypecodename,
   address3_city, address3_composite, address3_country, address3_county, address3_fax, address3_freighttermscode,
    address3_freighttermscodename, address3_latitude, address3_line1, address3_line2, address3_line3, address3_longitude, 
	address3_name, address3_postalcode, address3_postofficebox, address3_primarycontactname, address3_shippingmethodcode, 
	address3_shippingmethodcodename, address3_stateorprovince, address3_telephone1, address3_telephone2, address3_telephone3,
	 address3_upszone, address3_utcoffset, aging30, aging30_base, aging60, aging60_base, aging90, aging90_base, anniversary, 
	 annualincome, annualincome_base, assistantname, assistantphone, birthdate, business2, callback, childrensnames, 
	 company, CAST(contactid AS VARCHAR(50)) contactid, createdby, createdbyname, createdbyyominame, createdon, createdonbehalfby, createdonbehalfbyname,
	  createdonbehalfbyyominame, creditlimit, creditlimit_base, creditonhold, creditonholdname, customersizecode,
	   customersizecodename, customertypecode, customertypecodename, defaultpricelevelid, defaultpricelevelidname, 
	   department, description, donotbulkemail, donotbulkemailname, donotbulkpostalmail, donotbulkpostalmailname, donotemail, 
	   donotemailname, donotfax, donotfaxname, donotphone, donotphonename, donotpostalmail, donotpostalmailname, 
	   donotsendmarketingmaterialname, donotsendmm, educationcode, educationcodename, emailaddress1, emailaddress2, 
	   emailaddress3, employeeid, entityimage, entityimage_timestamp, entityimage_url, entityimageid, exchangerate, 
	   externaluseridentifier, familystatuscode, familystatuscodename, fax, firstname, ftpsiteurl, fullname, gendercode, 
	   gendercodename, governmentid, haschildrencode, haschildrencodename, home2, importsequencenumber, isbackofficecustomer, 
	   isbackofficecustomername, isprivatename, jobtitle, lastname, lastusedincampaign, leadsourcecode, leadsourcecodename, managername, managerphone, mastercontactidname,
	    mastercontactidyominame, masterid, merged, mergedname, middlename, mobilephone, modifiedby, modifiedbyname, modifiedbyyominame, modifiedon, modifiedonbehalfby, modifiedonbehalfbyname,
		 modifiedonbehalfbyyominame, new_eml_partner, new_eml_partnername, new_invite_clubgift, new_invite_clubgiftname, new_invite_holidaycard, new_invite_holidaycardname, new_invite_holidaygift, 
	   new_invite_holidaygiftname, new_invite_presale, new_invite_presalename, new_invite_seasonendgift, new_invite_seasonendgiftname, new_invite_suitegift, new_invite_suitegiftname, new_invite_travel, 
	   new_invite_travelname, new_invite_vip, new_invite_vipname, new_invite_vvip, new_invite_vvipname, new_manager_club, new_manager_clubname, new_manager_event, new_manager_eventname, new_manager_suites, new_manager_suitesname,
	    new_manager_suitetickets, new_manager_suiteticketsname, new_manager_tickets, new_manager_ticketsname, nickname, numberofchildren, originatingleadid, originatingleadidname, originatingleadidyominame, overriddencreatedon, ownerid, owneridname, 
		owneridtype, owneridyominame, owningbusinessunit, owningteam, owninguser, pager, parentcontactid, parentcontactidname, parentcontactidyominame, parentcustomerid, parentcustomeridname, parentcustomeridtype, parentcustomeridyominame, 
		participatesinworkflow, participatesinworkflowname, paymenttermscode, paymenttermscodename, preferredappointmentdaycode, preferredappointmentdaycodename, preferredappointmenttimecode, preferredappointmenttimecodename, preferredcontactmethodcode,
		 preferredcontactmethodcodename, preferredequipmentid, preferredequipmentidname, preferredserviceid, preferredserviceidname, preferredsystemuserid, preferredsystemuseridname, preferredsystemuseridyominame, processid, salutation, shippingmethodcode, 
		 shippingmethodcodename, spousesname, stageid, statecode, statecodename, statuscode, statuscodename, str_agerange, str_category, str_college, str_concertinterests, str_datawarehouseid, str_externalcapacitymodel, str_externalclustername,
		  str_externalprioritymodel, str_favoritedestination, str_favoriteplayer, str_favoriterestaurant, str_favoriteteam, str_hobbies, str_hometown, str_householdincome, str_householdincome_base, str_id, str_idtext, str_lastactivitydate,
		   str_marketingcontactsourceid, str_marketingcontactsourceidname, str_marketingcontacttypeid, str_marketingcontacttypeidname, str_musicclassical, str_musicclassicalname, str_musiccountry, str_musiccountryname, str_musicpop, str_musicpopname, 
		   str_musicrap, str_musicrapname, str_musicrock, str_musicrockname, str_neglectmeter, str_nextactivitydate, str_nextactivitysubject, str_number, str_openactivitycount, str_openticketcase, str_openticketcasename, str_openticketopportunity, 
		   str_openticketopportunityname, str_oppdaysinstage, str_oppproduct, str_oppsource, str_oppstage, str_otherinformation, str_partnerid, str_partneridname, str_partneridyominame, str_premiumtype, str_premiumtypename, str_priority, str_rating, 
		   str_ratingname, str_score, str_search, str_select, str_selectname, str_serviceperson, str_servicepersonname, str_servicepersonyominame, str_showsfamily, str_showsfamilyname, str_since, str_source, str_sportsinterests, str_test,
		    str_test_date, str_test_state, str_ticketeventtotalall, str_ticketeventtotalarena, str_ticketeventtotallast, str_ticketeventtotalthis, str_ticketnumberaverageall, str_ticketnumberaveragearena, str_ticketnumberaveragelast, 
			str_ticketnumberaveragethis, str_ticketnumbertotalall, str_ticketnumbertotalarena, str_ticketnumbertotallast, str_ticketnumbertotalthis, str_ticketpriceaverageall, str_ticketpriceaverageall_base, str_ticketpriceaveragearena, 
			str_ticketpriceaveragearena_base, str_ticketpriceaveragelast, str_ticketpriceaveragelast_base, str_ticketpriceaveragethis, str_ticketpriceaveragethis_base, str_ticketspendaverageall, str_ticketspendaverageall_base, str_ticketspendaveragearena,
			 str_ticketspendaveragearena_base, str_ticketspendaveragelast, str_ticketspendaveragelast_base, str_ticketspendaveragethis, str_ticketspendaveragethis_base, str_ticketspendtotalall, str_ticketspendtotalall_base, str_ticketspendtotalarena, str_ticketspendtotalarena_base, str_ticketspendtotallast, str_ticketspendtotallast_base, str_ticketspendtotalthis, 
			 str_ticketspendtotalthis_base, suffix, telephone1, telephone2, telephone3, territorycode, territorycodename, timezoneruleversionnumber, transactioncurrencyid, transactioncurrencyidname, traversedpath, utcconversiontimezonecode, versionnumber,
			  websiteurl, yomifirstname, yomifullname, yomilastname, yomimiddlename, CopyLoadDate, new_ssbcrmsystemacctid, new_ssbcrmsystemarchticsids, new_ssbcrmsystemcontactid, new_ssbcrmsystemDimcustomerIds, new_ssbcrmsystemSSIDWinner 
			  FROM ProdCopy.Contact WHERE 1=1 AND statecode = 0
GO
