CREATE TABLE [prodcopy].[Contact_vw]
(
[str_marketingcontacttypeidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionCurrencyIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredSystemUserIdName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partneridYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_servicepersonYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_marketingcontactsourceidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterContactIdYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredEquipmentIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredSystemUserIdYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_servicepersonName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterContactIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginatingLeadIdYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partneridName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredServiceIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultPriceLevelIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginatingLeadIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_AddressTypeCode] [int] NULL,
[Address1_City] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Country] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_County] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_AddressId] [uniqueidentifier] NULL,
[Address1_Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_FreightTermsCode] [int] NULL,
[Address1_Latitude] [float] NULL,
[Address1_Line1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line3] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Longitude] [float] NULL,
[Address1_Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostalCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostOfficeBox] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PrimaryContactName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_ShippingMethodCode] [int] NULL,
[Address1_StateOrProvince] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_UPSZone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_UTCOffset] [int] NULL,
[Address2_AddressTypeCode] [int] NULL,
[Address2_City] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Country] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_County] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_AddressId] [uniqueidentifier] NULL,
[Address2_Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_FreightTermsCode] [int] NULL,
[Address2_Latitude] [float] NULL,
[Address2_Line1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Line2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Line3] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Longitude] [float] NULL,
[Address2_Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_PostalCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_PostOfficeBox] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_PrimaryContactName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_ShippingMethodCode] [int] NULL,
[Address2_StateOrProvince] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_UPSZone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_UTCOffset] [int] NULL,
[OwnerId] [uniqueidentifier] NULL,
[OwnerIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdDsc] [int] NULL,
[OwnerIdType] [int] NULL,
[OwningUser] [uniqueidentifier] NULL,
[OwningTeam] [uniqueidentifier] NULL,
[AccountId] [uniqueidentifier] NULL,
[AccountIdName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountIdYomiName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentContactId] [uniqueidentifier] NULL,
[ParentContactIdName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentContactIdYomiName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactId] [uniqueidentifier] NULL,
[DefaultPriceLevelId] [uniqueidentifier] NULL,
[CustomerSizeCode] [int] NULL,
[CustomerTypeCode] [int] NULL,
[PreferredContactMethodCode] [int] NULL,
[LeadSourceCode] [int] NULL,
[OriginatingLeadId] [uniqueidentifier] NULL,
[OwningBusinessUnit] [uniqueidentifier] NULL,
[PaymentTermsCode] [int] NULL,
[ShippingMethodCode] [int] NULL,
[ParticipatesInWorkflow] [bit] NULL,
[IsBackofficeCustomer] [bit] NULL,
[Salutation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NickName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiFirstName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiMiddleName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiLastName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Anniversary] [datetime] NULL,
[BirthDate] [datetime] NULL,
[GovernmentId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiFullName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderCode] [int] NULL,
[AnnualIncome] [money] NULL,
[HasChildrenCode] [int] NULL,
[EducationCode] [int] NULL,
[WebSiteUrl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FamilyStatusCode] [int] NULL,
[FtpSiteUrl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpousesName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPhone] [bit] NULL,
[ManagerName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManagerPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotFax] [bit] NULL,
[DoNotEMail] [bit] NULL,
[DoNotPostalMail] [bit] NULL,
[DoNotBulkEMail] [bit] NULL,
[DoNotBulkPostalMail] [bit] NULL,
[AccountRoleCode] [int] NULL,
[TerritoryCode] [int] NULL,
[IsPrivate] [bit] NULL,
[CreditLimit] [money] NULL,
[CreatedOn] [datetime] NULL,
[CreditOnHold] [bit] NULL,
[CreatedBy] [uniqueidentifier] NULL,
[ModifiedOn] [datetime] NULL,
[ModifiedBy] [uniqueidentifier] NULL,
[NumberOfChildren] [int] NULL,
[ChildrensNames] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VersionNumber] [binary] (8) NULL,
[MobilePhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pager] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aging30] [money] NULL,
[StateCode] [int] NULL,
[Aging60] [money] NULL,
[StatusCode] [int] NULL,
[Aging90] [money] NULL,
[PreferredSystemUserId] [uniqueidentifier] NULL,
[PreferredServiceId] [uniqueidentifier] NULL,
[MasterId] [uniqueidentifier] NULL,
[PreferredAppointmentDayCode] [int] NULL,
[PreferredAppointmentTimeCode] [int] NULL,
[DoNotSendMM] [bit] NULL,
[ParentCustomerId] [uniqueidentifier] NULL,
[Merged] [bit] NULL,
[ExternalUserIdentifier] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriptionId] [uniqueidentifier] NULL,
[PreferredEquipmentId] [uniqueidentifier] NULL,
[LastUsedInCampaign] [datetime] NULL,
[ParentCustomerIdName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentCustomerIdType] [int] NULL,
[TransactionCurrencyId] [uniqueidentifier] NULL,
[OverriddenCreatedOn] [datetime] NULL,
[ExchangeRate] [numeric] (23, 10) NULL,
[ImportSequenceNumber] [int] NULL,
[TimeZoneRuleVersionNumber] [int] NULL,
[UTCConversionTimeZoneCode] [int] NULL,
[AnnualIncome_Base] [money] NULL,
[CreditLimit_Base] [money] NULL,
[Aging60_Base] [money] NULL,
[Aging90_Base] [money] NULL,
[Aging30_Base] [money] NULL,
[ParentCustomerIdYomiName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfBy] [uniqueidentifier] NULL,
[ModifiedOnBehalfBy] [uniqueidentifier] NULL,
[IsAutoCreate] [bit] NULL,
[str_ticketpriceaveragethis_Base] [money] NULL,
[STR_NextActivitydate] [datetime] NULL,
[STR_TicketNumberAverageArena] [numeric] (23, 10) NULL,
[str_ticketspendtotalthis_Base] [money] NULL,
[STR_college] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_musicclassical] [bit] NULL,
[STR_concertinterests] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_TicketEventTotalThis] [int] NULL,
[STR_TicketSpendAverageLast] [money] NULL,
[STR_priority] [int] NULL,
[STR_LastActivitydate] [datetime] NULL,
[STR_otherinformation] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_TicketEventTotalAll] [int] NULL,
[STR_musicrock] [bit] NULL,
[str_householdincome_Base] [money] NULL,
[str_ticketspendaveragearena_Base] [money] NULL,
[STR_favoriteteam] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_favoriterestaurant] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_hometown] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_hobbies] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ticketpriceaverageall_Base] [money] NULL,
[STR_category] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_since] [datetime] NULL,
[str_serviceperson] [uniqueidentifier] NULL,
[str_partnerid] [uniqueidentifier] NULL,
[STR_musiccountry] [bit] NULL,
[STR_TicketSpendTotalAll] [money] NULL,
[STR_TicketSpendAverageArena] [money] NULL,
[STR_TicketNumberAverageLast] [numeric] (23, 10) NULL,
[str_ticketspendaverageall_Base] [money] NULL,
[STR_search] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_TicketNumberTotalArena] [int] NULL,
[STR_number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_TicketNumberTotalLast] [int] NULL,
[STR_tier] [int] NULL,
[str_marketingcontactsourceid] [uniqueidentifier] NULL,
[STR_score] [int] NULL,
[STR_source] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_TicketSpendTotalThis] [money] NULL,
[STR_favoritedestination] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ticketspendaveragelast_Base] [money] NULL,
[STR_TicketNumberAverageAll] [numeric] (23, 10) NULL,
[str_ticketpriceaveragearena_Base] [money] NULL,
[str_ticketpriceaveragelast_Base] [money] NULL,
[str_ticketspendaveragethis_Base] [money] NULL,
[STR_TicketSpendAverageAll] [money] NULL,
[STR_favoriteplayer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_TicketPriceAverageThis] [money] NULL,
[STR_musicrap] [bit] NULL,
[STR_id] [int] NULL,
[STR_Rating] [int] NULL,
[STR_TicketNumberTotalThis] [int] NULL,
[STR_TicketSpendTotalLast] [money] NULL,
[STR_openticketopportunity] [bit] NULL,
[STR_HouseholdIncome] [money] NULL,
[STR_showsfamily] [bit] NULL,
[str_marketingcontacttypeid] [uniqueidentifier] NULL,
[str_ticketspendtotalall_Base] [money] NULL,
[STR_TicketPriceAverageAll] [money] NULL,
[STR_TicketPriceAverageLast] [money] NULL,
[STR_sportsinterests] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ticketspendtotalarena_Base] [money] NULL,
[STR_TicketSpendAverageThis] [money] NULL,
[STR_Select] [bit] NULL,
[STR_TicketEventTotalLast] [int] NULL,
[STR_TicketPriceAverageArena] [money] NULL,
[STR_musicpop] [bit] NULL,
[str_ticketspendtotallast_Base] [money] NULL,
[STR_TicketEventTotalArena] [int] NULL,
[STR_TicketNumberAverageThis] [numeric] (23, 10) NULL,
[STR_TicketNumberTotalAll] [int] NULL,
[STR_idtext] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_TicketSpendTotalArena] [money] NULL,
[str_openticketcase] [bit] NULL,
[str_clientaccountemployeesize] [int] NULL,
[str_clientaccountindustry] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientaccountsalesvolume] [money] NULL,
[str_clientaccountsalesvolume_Base] [money] NULL,
[str_clientaccountwebsite] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Event_DraftParty] [bit] NULL,
[new_Event_TrainingCamp] [bit] NULL,
[new_Event_SuiteGift] [bit] NULL,
[new_Event_ClubGift] [bit] NULL,
[new_Event_SeasonEndingGift] [bit] NULL,
[new_Event_HolidayCardPrint] [bit] NULL,
[new_Event_HolidayCardEmail] [bit] NULL,
[new_Event_HolidayGiftExperience] [bit] NULL,
[str_clientrenewed] [bit] NULL,
[cdi_age] [int] NULL,
[cdi_allowtextmessages] [bit] NULL,
[cdi_facebook] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_grade] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_identifiedon] [datetime] NULL,
[cdi_image] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_ip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_latitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_Longitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_partitionkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_rowkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_score] [int] NULL,
[cdi_totalscore] [int] NULL,
[cdi_twitter] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_visitorkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_birthyear] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Income_Range] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Net_Worth_Range] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_event_attend] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_VikingsNews] [bit] NULL,
[new_kp_NewMinnesotaStadiumEmail] [bit] NULL,
[new_kp_DiscountsandRewards] [bit] NULL,
[new_kp_personicx_cluster] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_email_rep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_phone_rep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_name_rep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SG_KP] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Date_of_Birth_kp] [datetime] NULL,
[new_USBankStadiumEvents] [bit] NULL,
[new_kp_gender] [int] NULL,
[new_kp_game] [int] NULL,
[new_kp_game_pass_code] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_VikingsAffiliation] [int] NULL,
[new_RSVP_kp] [int] NULL
)
GO
