CREATE TABLE [prodcopy].[ContactExtensionBase_0908]
(
[ContactId] [uniqueidentifier] NULL,
[STR_category] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_concertinterests] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_favoritedestination] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_favoriteplayer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_favoriterestaurant] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_favoriteteam] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_hobbies] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_hometown] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_id] [int] NULL,
[STR_source] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_sportsinterests] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_serviceperson] [uniqueidentifier] NULL,
[STR_college] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_musicclassical] [bit] NULL,
[STR_musiccountry] [bit] NULL,
[STR_musicpop] [bit] NULL,
[STR_musicrock] [bit] NULL,
[STR_number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_search] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_tier] [int] NULL,
[STR_priority] [int] NULL,
[STR_since] [datetime] NULL,
[STR_HouseholdIncome] [money] NULL,
[str_householdincome_Base] [money] NULL,
[STR_LastActivitydate] [datetime] NULL,
[STR_NextActivitydate] [datetime] NULL,
[STR_otherinformation] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Rating] [int] NULL,
[STR_score] [int] NULL,
[STR_Select] [bit] NULL,
[STR_TicketEventTotalAll] [int] NULL,
[STR_TicketEventTotalArena] [int] NULL,
[STR_TicketEventTotalLast] [int] NULL,
[STR_TicketEventTotalThis] [int] NULL,
[STR_TicketNumberAverageAll] [numeric] (23, 10) NULL,
[STR_TicketNumberAverageArena] [numeric] (23, 10) NULL,
[STR_TicketNumberAverageLast] [numeric] (23, 10) NULL,
[STR_TicketNumberAverageThis] [numeric] (23, 10) NULL,
[STR_TicketNumberTotalAll] [int] NULL,
[STR_TicketNumberTotalArena] [int] NULL,
[STR_TicketNumberTotalLast] [int] NULL,
[STR_TicketNumberTotalThis] [int] NULL,
[STR_TicketPriceAverageAll] [money] NULL,
[str_ticketpriceaverageall_Base] [money] NULL,
[STR_TicketPriceAverageArena] [money] NULL,
[str_ticketpriceaveragearena_Base] [money] NULL,
[STR_TicketPriceAverageLast] [money] NULL,
[str_ticketpriceaveragelast_Base] [money] NULL,
[STR_TicketPriceAverageThis] [money] NULL,
[str_ticketpriceaveragethis_Base] [money] NULL,
[STR_TicketSpendAverageAll] [money] NULL,
[str_ticketspendaverageall_Base] [money] NULL,
[STR_TicketSpendAverageArena] [money] NULL,
[str_ticketspendaveragearena_Base] [money] NULL,
[STR_TicketSpendAverageLast] [money] NULL,
[str_ticketspendaveragelast_Base] [money] NULL,
[STR_TicketSpendAverageThis] [money] NULL,
[str_ticketspendaveragethis_Base] [money] NULL,
[STR_TicketSpendTotalAll] [money] NULL,
[str_ticketspendtotalall_Base] [money] NULL,
[STR_TicketSpendTotalArena] [money] NULL,
[str_ticketspendtotalarena_Base] [money] NULL,
[STR_TicketSpendTotalLast] [money] NULL,
[str_ticketspendtotallast_Base] [money] NULL,
[STR_TicketSpendTotalThis] [money] NULL,
[str_ticketspendtotalthis_Base] [money] NULL,
[str_partnerid] [uniqueidentifier] NULL,
[STR_idtext] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_musicrap] [bit] NULL,
[STR_openticketopportunity] [bit] NULL,
[STR_showsfamily] [bit] NULL,
[str_marketingcontacttypeid] [uniqueidentifier] NULL,
[str_marketingcontactsourceid] [uniqueidentifier] NULL,
[str_openticketcase] [bit] NULL,
[str_clientaccountemployeesize] [int] NULL,
[str_clientaccountindustry] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientaccountsalesvolume] [money] NULL,
[str_clientaccountsalesvolume_Base] [money] NULL,
[str_clientaccountwebsite] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Event_DraftParty] [bit] NULL,
[new_Event_TrainingCamp] [bit] NULL,
[new_Event_SuiteGift] [bit] NULL,
[new_Event_ClubGift] [bit] NULL,
[new_Event_SeasonEndingGift] [bit] NULL,
[new_Event_HolidayCardPrint] [bit] NULL,
[new_Event_HolidayCardEmail] [bit] NULL,
[new_Event_HolidayGiftExperience] [bit] NULL,
[str_clientrenewed] [bit] NULL,
[cdi_age] [int] NULL,
[cdi_allowtextmessages] [bit] NULL,
[cdi_facebook] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_grade] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_identifiedon] [datetime] NULL,
[cdi_image] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_ip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_latitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_Longitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_partitionkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_rowkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_score] [int] NULL,
[cdi_totalscore] [int] NULL,
[cdi_twitter] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_visitorkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_birthyear] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Income_Range] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Net_Worth_Range] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_event_attend] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_VikingsNews] [bit] NULL,
[new_kp_NewMinnesotaStadiumEmail] [bit] NULL,
[new_kp_DiscountsandRewards] [bit] NULL,
[new_kp_personicx_cluster] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_email_rep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_phone_rep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_kp_name_rep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SG_KP] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Date_of_Birth_kp] [datetime] NULL,
[new_USBankStadiumEvents] [bit] NULL,
[new_kp_gender] [int] NULL,
[new_kp_game] [int] NULL,
[new_kp_game_pass_code] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_VikingsAffiliation] [int] NULL,
[new_RSVP_kp] [int] NULL
)
GO
