CREATE TABLE [prodcopy].[STR_ticketopportunity]
(
[STR_ticketopportunitytypeidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountidYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_pricelevelidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ticketstageidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ContactIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ContactIdYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountidName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_TicketProductIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_CampaignIdName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionCurrencyIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ticketsourceidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerId] [uniqueidentifier] NULL,
[OwnerIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdDsc] [int] NULL,
[OwnerIdType] [int] NULL,
[OwningUser] [uniqueidentifier] NULL,
[OwningTeam] [uniqueidentifier] NULL,
[STR_ticketopportunityId] [uniqueidentifier] NOT NULL,
[CreatedOn] [datetime] NULL,
[CreatedBy] [uniqueidentifier] NULL,
[ModifiedOn] [datetime] NULL,
[ModifiedBy] [uniqueidentifier] NULL,
[CreatedOnBehalfBy] [uniqueidentifier] NULL,
[ModifiedOnBehalfBy] [uniqueidentifier] NULL,
[OwningBusinessUnit] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statuscode] [int] NULL,
[VersionNumber] [binary] (8) NULL,
[ImportSequenceNumber] [int] NULL,
[OverriddenCreatedOn] [datetime] NULL,
[TimeZoneRuleVersionNumber] [int] NULL,
[UTCConversionTimeZoneCode] [int] NULL,
[STR_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_comments] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_daysinstage] [int] NULL,
[STR_dayssincecreation] [int] NULL,
[STR_event] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Events] [int] NULL,
[STR_LastActivity] [datetime] NULL,
[STR_NextActivity] [datetime] NULL,
[STR_ordernumber] [int] NULL,
[STR_Quantity] [int] NULL,
[STR_Revenue] [money] NULL,
[TransactionCurrencyId] [uniqueidentifier] NULL,
[ExchangeRate] [numeric] (23, 10) NULL,
[str_revenue_Base] [money] NULL,
[STR_stage10date] [datetime] NULL,
[STR_stage10text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage1date] [datetime] NULL,
[STR_stage1text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage2date] [datetime] NULL,
[STR_stage2text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage3date] [datetime] NULL,
[STR_stage3text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage4date] [datetime] NULL,
[STR_stage4text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage5date] [datetime] NULL,
[STR_stage5text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage6date] [datetime] NULL,
[STR_stage6text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage7date] [datetime] NULL,
[STR_stage7text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage8date] [datetime] NULL,
[STR_stage8text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage9date] [datetime] NULL,
[STR_stage9text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountid] [uniqueidentifier] NULL,
[STR_CampaignId] [uniqueidentifier] NULL,
[STR_ContactId] [uniqueidentifier] NULL,
[STR_pricelevelid] [uniqueidentifier] NULL,
[STR_ticketopportunitytypeid] [uniqueidentifier] NULL,
[STR_TicketProductId] [uniqueidentifier] NULL,
[STR_ticketsourceid] [uniqueidentifier] NULL,
[STR_ticketstageid] [uniqueidentifier] NULL,
[str_clientpaymentoption] [int] NULL,
[str_clientcontactid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Aisle] [bit] NULL,
[str_clientzone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [prodcopy].[STR_ticketopportunity] ADD CONSTRAINT [PK__STR_tick__6D2B336AB363176D] PRIMARY KEY CLUSTERED  ([STR_ticketopportunityId])
GO
