CREATE TABLE [prodcopy].[str_ticketopp_0908]
(
[STR_ticketopportunityId] [uniqueidentifier] NULL,
[STR_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_comments] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_daysinstage] [int] NULL,
[STR_dayssincecreation] [int] NULL,
[STR_event] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Events] [int] NULL,
[STR_LastActivity] [datetime] NULL,
[STR_NextActivity] [datetime] NULL,
[STR_ordernumber] [int] NULL,
[STR_Quantity] [int] NULL,
[STR_Revenue] [money] NULL,
[str_revenue_Base] [money] NULL,
[STR_stage10date] [datetime] NULL,
[STR_stage10text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage1date] [datetime] NULL,
[STR_stage1text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage2date] [datetime] NULL,
[STR_stage2text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage3date] [datetime] NULL,
[STR_stage3text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage4date] [datetime] NULL,
[STR_stage4text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage5date] [datetime] NULL,
[STR_stage5text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage6date] [datetime] NULL,
[STR_stage6text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage7date] [datetime] NULL,
[STR_stage7text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage8date] [datetime] NULL,
[STR_stage8text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_stage9date] [datetime] NULL,
[STR_stage9text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountid] [uniqueidentifier] NULL,
[STR_CampaignId] [uniqueidentifier] NULL,
[STR_ContactId] [uniqueidentifier] NULL,
[STR_pricelevelid] [uniqueidentifier] NULL,
[STR_ticketopportunitytypeid] [uniqueidentifier] NULL,
[STR_TicketProductId] [uniqueidentifier] NULL,
[STR_ticketsourceid] [uniqueidentifier] NULL,
[STR_ticketstageid] [uniqueidentifier] NULL,
[str_clientpaymentoption] [int] NULL,
[str_clientcontactid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Aisle] [bit] NULL,
[str_clientzone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
CREATE NONCLUSTERED INDEX [ticketopp] ON [prodcopy].[str_ticketopp_0908] ([str_clientcontactid])
GO
