CREATE TABLE [prodcopy].[AccountExtensionBase_BK]
(
[AccountId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_custom1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_custom2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_custom3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_custom4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_league1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_league2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_league3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_league4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_league5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_league6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_league7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_league8] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_serviceperson] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_budgetamount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_budgetamount_Base] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_budgetdate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_search] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partnersalesperson] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partnerserviceperson] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_premiumsalesperson] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_premiumserviceperson] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Select] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_leadsourcecode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_idtext] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_marketingaccountindustryid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_marketingaccountsourceid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientnewstadiumpartnersalespersonid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_allowtextmessages] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
