CREATE TABLE [prodcopy].[STR_ticketorder]
(
[TransactionCurrencyIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ContactIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ContactIdYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ServicepersonIdYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ticketaccountidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_pricelevelidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ServicepersonIdName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerId] [uniqueidentifier] NULL,
[OwnerIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdDsc] [int] NULL,
[OwnerIdType] [int] NULL,
[OwningUser] [uniqueidentifier] NULL,
[OwningTeam] [uniqueidentifier] NULL,
[STR_ticketorderId] [uniqueidentifier] NOT NULL,
[CreatedOn] [datetime] NULL,
[CreatedBy] [uniqueidentifier] NULL,
[ModifiedOn] [datetime] NULL,
[ModifiedBy] [uniqueidentifier] NULL,
[CreatedOnBehalfBy] [uniqueidentifier] NULL,
[ModifiedOnBehalfBy] [uniqueidentifier] NULL,
[OwningBusinessUnit] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statuscode] [int] NULL,
[VersionNumber] [binary] (8) NULL,
[ImportSequenceNumber] [int] NULL,
[OverriddenCreatedOn] [datetime] NULL,
[TimeZoneRuleVersionNumber] [int] NULL,
[UTCConversionTimeZoneCode] [int] NULL,
[STR_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Amount] [money] NULL,
[TransactionCurrencyId] [uniqueidentifier] NULL,
[ExchangeRate] [numeric] (23, 10) NULL,
[str_amount_Base] [money] NULL,
[STR_Category] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Code] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Date] [datetime] NULL,
[STR_Event] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_eventid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Events] [int] NULL,
[STR_First] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Id] [int] NULL,
[STR_Last] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Quantity] [int] NULL,
[STR_Row] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_seasonid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Section] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_Source] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_status] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_string1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_string2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_string3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_string4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_type] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ContactId] [uniqueidentifier] NULL,
[STR_pricelevelid] [uniqueidentifier] NULL,
[STR_ServicepersonId] [uniqueidentifier] NULL,
[STR_ticketaccountid] [uniqueidentifier] NULL
)
GO
ALTER TABLE [prodcopy].[STR_ticketorder] ADD CONSTRAINT [PK__STR_tick__5CEC361BA926F8FC] PRIMARY KEY CLUSTERED  ([STR_ticketorderId])
GO
