IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBCLOUD\ifuseini')
CREATE LOGIN [SSBCLOUD\ifuseini] FROM WINDOWS
GO
CREATE USER [SSBCLOUD\ifuseini] FOR LOGIN [SSBCLOUD\ifuseini] WITH DEFAULT_SCHEMA=[SSBCLOUD\ifuseini]
GO
REVOKE CONNECT TO [SSBCLOUD\ifuseini]
